### PR TITLE
Customize error pages

### PR DESCRIPTION
**Pull request by f-necas**
I'm not sure about the `/config` route. I did this way in order to let other applications to be able to retrieve config from the gateway.

Everything is customizable with the georchestraStylesheet set in default.properties from datadir.

Previews : 
image

image

In blue : 
image

### CODE REVIEW

**Comment by landryb** [comment]
I like the '500' -> maintenance shortcut, to avoid saying 'something is badly broken' ;)

**Comment by pmauduit** [comment]
> I like the '500' -> maintenance shortcut, to avoid saying 'something is badly broken' ;)

I'd have put a picture of you with your sysadmin teeshirt "like riding a bike, except that everything is in fire and you are in hell" ;-)

**Comment by fvanderbiest** [comment]
Not sure I fully understand what's at stake here.
Would you be able to develop in the PR description what it does and why ?
Ideally, people should not have to read the code to understand what the PR does ;-)

**Comment by fvanderbiest** [comment]
OK, got it, thanks !

**Comment by fvanderbiest** [comment]
Requesting @groldan 's review too

**Comment by groldan** [comment]
Almost fell off the bed when I just woke up and saw this notification saying you added a /config route to the gateway. Thought it was exposing the config service.
Please be more specific 😀, like in "Add a custom entry point to retrieve the error pages stylesheet..." or so. Same for the commits, it doesn't say much and commits arre independent of GitHub.
Other than that great work.

**Pull request merged**
